### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by hohonuuli** [mbari-org/oni#1]
```[tasklist]
### Tasks
- [ ] Endpoints to replicate existing kb and user API
- [ ] Add references
- [ ] Implement postgres
- [ ] Create migration for existing SQL Server db
- [ ] Create migration for existing postgres db
```

**Comment by hohonuuli** [comment]
Paul can use <https://github.com/mbari-org/m3-quickstart/tree/feature/oni> for development
